spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/simple_rest_api
    username: simple-rest-api
    password: 123456
    
  jpa:
    hibernate:
      ddl-auto: update

server:
  error:
    include-message: always